services:
  - type: web
    name: pdcms-patientcare
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pdcms-patientcare-db
          property: connectionString

databases:
  - name: pdcms-patientcare-db
    plan: starter
